/*
 * can-ids.h
 *
 *  Created on: 2020.04.29.
 *      Author: Szbuli
 */

#ifndef CAN_CAN_IDS_H_
#define CAN_CAN_IDS_H_

#define	SENSOR_TYPE_OFF 0
#define	SENSOR_TYPE_ALARM 1
#define	SENSOR_TYPE_COUNTER_NO 3
#define	SENSOR_TYPE_COUNTER_NC 4

#define	ALARM_CONTROLLER_DEVICE_ID	14
#define	ALARM_CONTROLLER_SENSOR_STATE_1	15
#define	ALARM_CONTROLLER_SENSOR_STATE_2	16
#define	ALARM_CONTROLLER_SENSOR_STATE_3	17
#define	ALARM_CONTROLLER_SENSOR_STATE_4	18
#define	ALARM_CONTROLLER_SENSOR_STATE_5	19
#define	ALARM_CONTROLLER_SENSOR_STATE_6	20
#define	ALARM_CONTROLLER_SENSOR_STATE_7	21
#define	ALARM_CONTROLLER_SENSOR_STATE_8	22
#define	ALARM_CONTROLLER_SENSOR_STATE_9	23
#define	ALARM_CONTROLLER_SENSOR_STATE_10	24
#define	ALARM_CONTROLLER_SENSOR_STATE_11	25
#define	ALARM_CONTROLLER_SENSOR_STATE_12	26
#define	ALARM_CONTROLLER_SENSOR_STATE_13	27
#define	ALARM_CONTROLLER_SENSOR_STATE_14	28
#define	ALARM_CONTROLLER_SENSOR_STATE_15	29
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_1	30
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_2	31
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_3	32
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_4	33
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_5	34
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_6	35
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_7	36
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_8	37
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_9	38
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_10	39
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_11	40
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_12	41
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_13	42
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_14	43
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_15	44
#define	ALARM_CONTROLLER_CONFIGURE_TAMPER	45
#define	ALARM_CONTROLLER_TAMPER	46
#define	ALARM_CONTROLLER_HEARTBEAT	47
#define	ALARM_CONTROLLER_FACTORY_RESET	48
#define	ALARM_CONTROLLER_CONFIGURE_HEARTBEAT	49

#define	ALARM_CONTROLLER_HA_ALARM_SENSOR_CONFIG	50
#define	ALARM_CONTROLLER_HA_STATUS_CONFIG	51
#define	ALARM_CONTROLLER_HA_CONFIGURE_SENSOR_TYPE_CONFIG	52
#define	ALARM_CONTROLLER_HA_CONFIGURE_COUNTER_VALUE_CONFIG	53

#define	ALARM_CONTROLLER_HA_COUNTER_SENSOR_CONFIG	70
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_1	80
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_2	81
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_3	82
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_4	83
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_5	84
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_6	85
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_7	86
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_8	87
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_9	88
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_10	89
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_11	90
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_12	91
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_13	92
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_14	93
#define	ALARM_CONTROLLER_COUNTER_SENSOR_STATE_15	94

#define	ALARM_CONTROLLER_COUNTER_SET_1	200
#define	ALARM_CONTROLLER_COUNTER_SET_2	201
#define	ALARM_CONTROLLER_COUNTER_SET_3	202
#define	ALARM_CONTROLLER_COUNTER_SET_4	203
#define	ALARM_CONTROLLER_COUNTER_SET_5	204
#define	ALARM_CONTROLLER_COUNTER_SET_6	205
#define	ALARM_CONTROLLER_COUNTER_SET_7	206
#define	ALARM_CONTROLLER_COUNTER_SET_8	207
#define	ALARM_CONTROLLER_COUNTER_SET_9	208
#define	ALARM_CONTROLLER_COUNTER_SET_10	209
#define	ALARM_CONTROLLER_COUNTER_SET_11	210
#define	ALARM_CONTROLLER_COUNTER_SET_12	211
#define	ALARM_CONTROLLER_COUNTER_SET_13	212
#define	ALARM_CONTROLLER_COUNTER_SET_14	213
#define	ALARM_CONTROLLER_COUNTER_SET_15	214


#endif /* CAN_CAN_IDS_H_ */
