/*
 * can-ids.h
 *
 *  Created on: 2020. ápr. 29.
 *      Author: Szbuli
 */

#ifndef CAN_CAN_IDS_H_
#define CAN_CAN_IDS_H_

#define	ALARM_CONTROLLER_DEVICE_ID	14
#define	ALARM_CONTROLLER_SENSOR_STATE_1	15
#define	ALARM_CONTROLLER_SENSOR_STATE_2	16
#define	ALARM_CONTROLLER_SENSOR_STATE_3	17
#define	ALARM_CONTROLLER_SENSOR_STATE_4	18
#define	ALARM_CONTROLLER_SENSOR_STATE_5	19
#define	ALARM_CONTROLLER_SENSOR_STATE_6	20
#define	ALARM_CONTROLLER_SENSOR_STATE_7	21
#define	ALARM_CONTROLLER_SENSOR_STATE_8	22
#define	ALARM_CONTROLLER_SENSOR_STATE_9	23
#define	ALARM_CONTROLLER_SENSOR_STATE_10	24
#define	ALARM_CONTROLLER_SENSOR_STATE_11	25
#define	ALARM_CONTROLLER_SENSOR_STATE_12	26
#define	ALARM_CONTROLLER_SENSOR_STATE_13	27
#define	ALARM_CONTROLLER_SENSOR_STATE_14	28
#define	ALARM_CONTROLLER_SENSOR_STATE_15	29
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_1	30
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_2	31
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_3	32
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_4	33
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_5	34
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_6	35
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_7	36
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_8	37
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_9	38
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_10	39
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_11	40
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_12	41
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_13	42
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_14	43
#define	ALARM_CONTROLLER_CONFIGURE_SENSOR_15	44
#define	ALARM_CONTROLLER_CONFIGURE_TAMPER	45
#define	ALARM_CONTROLLER_TAMPER	46
#define	ALARM_CONTROLLER_HEARTBEAT	47
#define	ALARM_CONTROLLER_FACTORY_RESET	48

#endif /* CAN_CAN_IDS_H_ */
